routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function () {
    return redirect()->route('dashboard.index');
})->middleware('auth');


Route::Group(['prefix' => 'dashboard', 'namespace' => 'Dashboard', 'middleware' => 'auth'], function () {

    route::get('/index', 'HomeController@index')->name('dashboard.index')->middleware('auth');


    //============= Provider Routes
    Route::resource('providers', 'ProviderController');

//    Route::Group([ 'middleware' => 'permissions'], function () {

        //============= Client Routes
        Route::resource('users', 'UserController');

        //============= Admin Routes
        Route::resource('admins', 'AdminController');


        //================ Notifications Routes =========
        Route::post('send/notify', 'NotificationController@sendNotify')->name('send_notify');


        //================ Address Routes =========
        Route::resource('address', 'AddressController');

        //==============City Routes
        Route::resource('city', 'CityController');


        //===============Category Routes
        Route::resource('categories', 'CategoryController');


        //============================= Products Routs ================================================
        Route::resource('products', 'ProductController');


        //=============== Advertise Routs==========================================
        Route::resource('advertises', 'AdvertisesController');


        //===============Settings Routs ============================================
        Route::get('settings', 'SettingController@index')->name('settings.index'); //
        Route::get('settings/update', 'SettingController@edit')->name('settings.edit');
        Route::post('settings', 'SettingController@update')->name('settings.update');

//});

    //=============================== Orders =====================================
    Route::resource('orders', 'OrderController');
    Route::get('orders/process/{order}', 'OrderController@process')->name('process.order');
    Route::get('orders/ship/{order}', 'OrderController@ship')->name('ship.order');
    Route::get('orders/deliver/{order}', 'OrderController@deliver')->name('deliver.order');


});

app/Http/Controllers/Dashboard/AddressController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Address;
use App\City;
use App\Http\Controllers\Controller;
use App\Http\Requests\dashboard\AddressRequest;
use Illuminate\Http\Request;

class AddressController extends Controller
{
    public function __construct()
    {
        return $this->mainReturn = 'dashboard.address.';
    }

    public function index()
    {
        $name = 'name_' . app()->getLocale();
        $description = 'description_' . app()->getLocale();

        if (auth()->user()->hasRole('admin')) {
            $addresses = Address::all();
        } else {
            $addresses  = auth()->user()->address;
        }

        return view($this->mainReturn . 'index', [
            'addresses' => $addresses,
            'name' => $name,
            'description' => $description,
        ]);
    }


    public function create()
    {
        $name = 'name_' . app()->getLocale();
        $description = 'description_' . app()->getLocale();
        return view($this->mainReturn . 'create', [
            'addresses' => Address::all(),
            'cities' => City::all(),
            'name' => $name,
            'description' => $description,
        ]);
    }


    public function store(AddressRequest $request)
    {
        $request_data = $request->except(['add', 'addNew']);
        $request_data['user_id'] = auth()->user()->id;

        Address::create($request_data);

        if ($request->add) {
            $back =  route('address.index');
        } else {
            $back = route('address.create');
        }
        return redirect($back)->with('success', trans('api.added_successfully'));
    }


    public function show(Address $address)
    {
        //
    }


    public function edit(Address $address)
    {
        $name = 'name_' . app()->getLocale();
        $description = 'description_' . app()->getLocale();
        return view($this->mainReturn . 'edit', [
            'address' => $address,
            'cities' => City::all(),
            'name' => $name,
            'description' => $description,
        ]);
    }


    public function update(AddressRequest $request, Address $address)
    {
        $address->update($request->all());
        return redirect()->route('address.index')->with('success', trans('api.updated_successfully'));
    }


    public function destroy(Address $address)
    {
        if (auth()->user()->address->count() == 1) {
            $address->delete();
            return redirect()->route('address.index')->with('success', trans('api.deleted_successfully'));
        } else {
            return redirect()->route('address.index')->with('error', trans('api.cant_deleted_add_more_first'));
        }
    }
}

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Category;
use App\City;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ImageController;
use App\Http\Requests\dashboard\AdminRequest;
use App\Order;
use App\Product;
use App\Setting;
use App\Token;
use App\User;
use Illuminate\Http\Request;
use JWTAuth;

class AdminController extends Controller
{


    public function __construct()
    {
        $this->mainRedirect = 'dashboard.admins.';
    }

    public function index(Request $request)
    {
        $admins = User::where('type', 'admin')->when($request->search, function ($query) use ($request) {
            return $query->where('full_name', 'like', '%' . $request->search . '%');
        })->latest()->paginate(4);

        return view($this->mainRedirect . 'index', [
            'admins' => $admins,
        ]);
    }


    public function create()
    {
        return view($this->mainRedirect . 'create', [
            'cities' => City::all(),
            'users' => User::all(),
            'categories' => Category::all(),
            'products' => Product::all(),
            'settings' => Setting::all(),
            'all-orders' => Order::all(),
        ]);
    }


    public function store(AdminRequest $request)
    {
        $request_data = $request->except(['password', 'password_confirmation', 'image', 'permissions']);
        $request_data['password'] = bcrypt($request->password);
        if ($request->image) {
            $request_data['image'] = ImageController::upload_single($request->image, 'uploads/users/');
        }
        $request_data['type'] = 'admin';
        $request_data['code'] = rand(0000, 9999);
        $admin = User::create($request_data);

        $admin->attachRole('admin');
        if ($request->permissions) {
            $admin->syncPermissions($request->permissions);
        }

        Token::create([
            'user_id' => $admin->id,
            'jwt' => JWTAuth::fromUser($admin),
        ]);
        return redirect()->route('admins.index')->with('success', 'تم الاضافة  بنجاح');
    }


    public function show(User $admin)
    {
        $name = 'name_' . app()->getLocale();
        $description = 'description_' . app()->getLocale();

        return view($this->mainRedirect . 'show', [
            'user' => $admin,
            'name' => $name,
            'description' => $description,
            'addresses' => $admin->address
        ]);
    }


    public function edit(User $admin)
    {
        return view($this->mainRedirect . 'edit', [
            'admin' => $admin,
            'cities' => City::all(),
        ]);
    }

    public function update(AdminRequest $request, User $admin)
    {
        $request_data = $request->except(['image', 'password', 'password_confirmation', 'permissions', 'address',]);
        $request_data['password'] = bcrypt($request->password);
        if ($request->image) {
            $image = $admin->image;
            ImageController::delete_image($image, 'users');
            $request_data['image'] = ImageController::upload_single($request->image, 'uploads/users/');
        }
        $admin->update($request_data);
        return redirect()->route('admins.index')->with('success', 'تم  التعديل بنجاح');

    }


    public function destroy(User $admin)
    {
        $image = $admin->image;
        $path = 'users';
        ImageController::delete_image($image, $path);
        $admin->delete();
        return redirect()->route('admins.index')->with('success', 'تم الحذف  بنجاح');
    }

}

app/Http/Controllers/Dashboard/AdvertisesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Advertise;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ImageController;
use App\Http\Requests\dashboard\AdvertiseRequest;
use Illuminate\Http\Request;

class AdvertisesController extends Controller
{

    public function index()
    {
        return view('dashboard.advertises.index', [
            'advertises' => Advertise::all(),
        ]);
    }


    public function create()
    {
        return view('dashboard.advertises.create', [
            'advertises' => Advertise::orderBy('created_at', 'desc')->get(),
        ]);
    }


    public function store(AdvertiseRequest $request)
    {
        $request_data = $request->except(['add', 'addNew','image']);
        if ($request->image) {

            $request_data['image'] = ImageController::upload_single($request->image, 'uploads/advertise/');
        }

        $request_data['user_id'] = auth()->user()->id;

        Advertise::create($request_data);

        if ($request->add) {
            $back =  route('advertises.index');
        } else {
            $back = route('advertises.create');
        }
        return redirect($back)->with('success', trans('api.added_successfully'));
    }


    public function show(Advertise $advertise)
    {
        //
    }


    public function edit(Advertise $advertise)
    {
        //
    }


    public function update(Request $request, Advertise $advertise)
    {
        //
    }


    public function destroy(Advertise $advertise)
    {
            $advertise->delete();
            return redirect()->route('advertises.index')->with('success', trans('api.deleted_successfully'));
    }

}

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ImageController;
use App\Http\Requests\CategoryRequest;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    public function __construct()
    {
        $this->mainRedirect = 'dashboard.categories.';
    }

    public function index(Request $request)
    {
        $categories =  Category::when($request->search, function ($query) use ($request) {
            return $query->where('name_ar', 'like', '%' . $request->search . '%')->orwhere('name_en', 'like', '%' . $request->search . '%');
        })->get();

        return view($this->mainRedirect . 'index', [
            'categories' => $categories
        ]);
    }


    public function create()
    {
        return view($this->mainRedirect . 'create', [
            'categories' => Category::latest()->take(10)->get(),
        ]);
    }


    public function store(CategoryRequest $request)
    {
        $request_data = $request->except(['add', 'addNew', 'image', 'number_inner_products']);
        if ($request->image) {

            $request_data['image'] = ImageController::upload_single($request->image, 'uploads/categories/');
        }
        Category::create($request_data);
        if ($request->add) {
            $back =  route('categories.index');
        } else {
            $back = route('categories.create');
        }
        return redirect($back)->with('success', 'تم اضافه القسم بنجاح');
    }

    public function show(Category $category)
    {
        //
    }


    public function edit(Category $category)
    {
        return view($this->mainRedirect . 'edit', [
            'category' => $category,
        ]);
    }


    public function update(CategoryRequest $request, Category $category)
    {
        $request_data = $request->except('image');
        if ($request->image) {
            ImageController::delete_image($category->image, 'categories');
            $request_data['image'] = ImageController::upload_single($request->image, 'uploads/categories/');
        }
        $category->update($request_data);
        return redirect()->route('categories.index')->with('success', 'تم تعديل القسم بنجاح');
    }


    public function destroy(Category $category)
    {
        ImageController::delete_image($category->image, 'categories');
        $category->delete();
        return redirect()->route('categories.index')->with('success', trans('site.deleted_successfully'));
    }
}

app/Http/Controllers/Dashboard/CityController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\City;
use App\Http\Requests\CityRequest;
use Illuminate\Http\Request;

class CityController extends Controller
{

    public function index()
    {
        return view('dashboard.city.index', [
            'cities' => City::all(),
        ]);
    }

    public function create()
    {
        return view('dashboard.city.create', [
            'cities' => City::all(),
        ]);
    }


    public function store(CityRequest $request)
    {
        $request_data = $request->except(['add', 'addNew']);
        City::create($request_data);
        if ($request->add) {
            $back =  route('city.index');
        } else {
            $back = route('city.create');
        }
        return redirect($back)->with('success', 'تم اضافه المدينه بنجاح');
    }

    public function show(City $city)
    {
        //
    }

    public function edit(City $city)
    {
        return view('dashboard.city.edit', [
            'city' => $city
        ]);
    }

    public function update(CityRequest $request, City $city)
    {
        $city->update([
            'name_ar' => $request->name_ar,
            'name_en' => $request->name_en,
        ]);
        return redirect()->route('city.index')->with('success', 'تم تعديل المدينه بنجاح');
    }

    public function destroy(City $city)
    {
        $city->delete();
        return redirect()->route('city.index')->with('success', 'تم حذف المدينه بنجاح');
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Advertise;
use App\Category;
use App\City;
use App\Http\Controllers\Controller;
use App\Order;
use App\Product;
use App\User;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        $name = 'name_' . app()->getLocale();
        $description = 'description_' . app()->getLocale();
        $users = User::where('type', 'client');
        $providers = User::where('type', 'provider');
        $all_products = Product::all();
        $latest_products = Product::latest()->paginate(3);
        $most_products = Product::orderBy('ordered_count', 'asc')->latest()->paginate(3);
        $orders = Order::all();
        $advertises = Advertise::all();
        $cities = City::all();
        $categories = Category::all();

        return view('dashboard.index', [
            'users' => $users,
            'providers' => $providers,
            'all_products' => $all_products,
            'latest_products' => $latest_products,
            'most_products' => $most_products,
            'orders' => $orders,
            'advertises' => $advertises,
            'cities' => $cities,
            'description' => $description,
            'name' => $name,
            'categories' => $categories,
        ]);

    }
}

resources/views/dashboard/admins/create.blade.php
@extends('dashboard.layouts.master')
@section('content')

@section('header')
    <h1>
        @lang('site.dashboard')
        <small>@lang('site.control_panel') </small>
    </h1>
    <ol class="breadcrumb">

        <li class="#"><a href="{{ route('dashboard.index') }}">@lang('site.dashboard')</a></li>
        <li class="active"><a href="{{ route('admins.index') }}">@lang('site.admins')</a></li>
        <li class="active"><a href="{{ route('admins.create') }}">@lang('site.create_admins')</a></li>
    </ol>
@endsection

@include('dashboard.layouts.includes.errors')

<form action=" {{ route('admins.store') }} " method="POST" enctype="multipart/form-data">
    @csrf

    <div class="box-body">
        <div>
            <label for=""> @lang('site.main_info') </label>

            <div class="form-group">

                <input type="text" class="form-control" name="full_name" placeholder="@lang('site.full_name')">
            </div>

            <div class="form-group">

                <input type="email" class="form-control" name="email" placeholder="@lang('site.email')">
            </div>

            <div class="form-group">

                <input type="text" class="form-control" name="mobile" placeholder="@lang('site.mobile')">
            </div>

            <div class="form-group">
                <select name="city_id" id="" class="form-control">
                    <option value="" disabled selected> {{trans('site.cities')}} </option>
                    @foreach($cities as $city)
                        <option value="{{$city->id}}">{{$city->name_ar}}-{{$city->name_en}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password" placeholder="@lang('site.password')">
            </div>

            <div class="form-group">

                <input type="password" class="form-control" name="password_confirmation"
                       placeholder="@lang('site.password_confirmation')">

            </div>

            <div class="form-group">
                <label>@lang('site.image')</label>
                <input type="file" class="form-control image " name="image">
            </div>

            <div class="form-group">
                <img src=" {{ asset('public/uploads/default.png') }} " width=" 100px " class="thumbnail image-preview">
            </div>

            <div class="form-group">
                <label for="">@lang('site.permissions')</label>
                @php
                    $models = ['users','cities','categories','products',];
                    $maps =['create','read','update','delete'];
                @endphp
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        @foreach($models as $index=>$model)
                            <li class="{{ $index == 0 ? 'active' : '' }}"><a href="#{{$model}}"
                                                                             data-toggle="tab"> @lang('site.'.$model)</a>
                            </li>
                        @endforeach
                    </ul>
                    <div class="tab-content">
                        @foreach($models as $index=>$model)
                            <div class="tab-pane {{ $index == 0 ? 'active' : '' }}" id="{{$model}}">
                                @foreach($maps as $map)
                                    <label for=""> <input type="checkbox" name="permissions[]"
                                                          value="{{$map}}_{{$model}}"> @lang('site.'.$map) </label><br>
                                @endforeach
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="box-footer">

        <button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i> {{trans('site.add')}}</button>

    </div>


</form>

@endsection

resources/views/dashboard/admins/edit.blade.php
@extends('dashboard.layouts.master')
@section('content')

@section('header')
<h1>
    @lang('site.dashboard')
    <small>@lang('site.control_panel') </small>
</h1>
<ol class="breadcrumb">

    <li class="#"> <a href="{{ route('dashboard.index') }}">@lang('site.dashboard')</a></li>
    <li class="#"><a href="{{ route('admins.index') }}">@lang('site.admins')</a></li>
</ol>
@endsection

@include('dashboard.layouts.includes.errors')

<div class="row">
    <div class="col-md-6">
        <form action=" {{ route('admins.update',$admin) }} " method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="box-body">



                <div class="form-group">

                    <input type="text" class="form-control" value="{{$admin->full_name}}" name="full_name" placeholder="@lang('site.full_name')">
                </div>

                <div class="form-group">

                    <input type="email" class="form-control" value="{{$admin->email}}" name="email" placeholder="@lang('site.email')">
                </div>


                <div class="form-group">
                    <select name="city_id" id="" class="form-control">
                        <option value="" disabled selected> {{trans('site.cities')}} </option>
                        @foreach($cities as $city)
                            <option value="{{$city->id}}">{{$city->name_ar}}-{{$city->name_en}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label>@lang('site.image')</label>
                    <input type="file" class="form-control image " name="image">
                </div>

                <div class="form-group">
                    <img src=" {{ asset('public/uploads/default.png') }} " width=" 100px " class="thumbnail image-preview">
                </div>

                <div class="form-group">

                    <input type="password" class="form-control" name="password" placeholder="@lang('site.password')">
                </div>

                <div class="form-group">

                    <input type="password" class="form-control" name="password_confirmation" placeholder="@lang('site.password_confirmation')">

                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary"> <i class="fa fa-edit"></i> @lang('site.edit')</button>
                </div>


            </div>
        </form>
    </div>




</div>


@endsection

resources/views/dashboard/admins/index.blade.php
@extends('dashboard.layouts.master')
@section('content')

@section('header')
<h1>
    @lang('site.dashboard')
    <small>@lang('site.control_panel') </small>
</h1>
<ol class="breadcrumb">

    <li class="#"> <a href="{{ route('dashboard.index') }}">@lang('site.dashboard')</a></li>
    <li class="active"><a href="{{ route('admins.index') }}">@lang('site.admins')</a></li>
</ol>
@endsection


<div class="box box-primary">
    @include('dashboard.layouts.includes.errors')

    <div class="box-header with-border">
        <h3 class="box-title"> @lang('admins') </h3> <small>{{$admins->total() != null ? $admins->total() : 0 }}</small>
        <form action="{{ route('admins.index') }}" method="get">

            <div class="row">
                <div class="col-md-4">
                    <input type="text" name="search" class="form-control" placeholder="@lang('site.search')" value="{{request()->search}}">
                </div>
                <div class="col-md-4">
                    <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-search"></i> @lang('site.search') </button>
                    <a href="{{ route('admins.create') }}" class="btn btn-info btn-sm"><i class="fa fa-plus"></i> @lang('site.create') </a>
                </div>
            </div>
        </form>

    </div>

    <div class="box-body">
        @if($admins->count() > 0)

        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th> # </th>
                    <th> @lang('site.full_name') </th>
                    <th> @lang('site.email') </th>
                    <th> @lang('site.type') </th>
                    <th> @lang('site.city') </th>
                    <th> @lang('site.image') </th>
                    <th> @lang('site.action') </th>
                </tr>
            </thead>
            <tbody>
                @foreach($admins as $index=>$admin )
                <tr>
                    <td> {{ $index+1 }} </td>
                    <td> {{ $admin->full_name }} </td>
                    <td> {{ $admin->email }} </td>
                    <td> {{ $admin->type }} </td>
                    @if($admin->city_id != null)
                    <td> {{ $admin->city->name_ar }}-{{ $admin->city->name_en }} </td>
                    @else
                    <td> Admin City </td>
                    @endif
                    <td><img src="{{ $admin->ImagePath }}" style="width: 80px ; height:80px"></td>
                    <td>
                        <a href=" {{route('admins.edit',$admin->id)}} " class="btn btn-info btn-sm"> <i class="fas fa-edit"></i> @lang('site.edit') </a>
                        <a href=" {{route('admins.show',$admin->id)}} " class="btn btn-warning btn-sm"> <i class="fas fa-eye"></i> @lang('site.see_more') </a>
                        <form action=" {{ route('admins.destroy',$admin->id) }} " method="POST" style="display:inline-block">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm delete"> <i class="fa fa-trash"></i> @lang('site.delete') </button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {{$admins->appends(request()->query())->links()}}
        @else

        <h2> @lang('site.no_data_found') </h2>

        @endif

    </div>
</div>
@endsection

resources/views/dashboard/admins/show.blade.php
@extends('dashboard.layouts.master')
@section('content')
@section('header')
    <h1>
        @lang('site.dashboard')
        <small>@lang('site.control_panel') </small>
    </h1>
    <ol class="breadcrumb">
    </ol>
@endsection

<!-- Content Wrapper. Contains page content -->

<section class="content-header">
    @include('dashboard.layouts.includes.errors')
    <h1>
        {{$user->full_name}}
    </h1>
    <ol class="breadcrumb">
        <li class="#"><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i>@lang('site.dashboard')
            </a></li>
        <li class="active"><a href="{{ route('admins.index') }}">@lang('site.admins')</a></li>
    </ol>
</section>

<section class="content">

    <div class="row">
        <div class="col-md-3">
            <!------------------------------------------------------- start about ---------------------------------------->
            <div class="box box-primary">
                <div class="box-body box-profile">
                    <img class="profile-user-img img-responsive img-circle" src="{{$user->ImagePath}}"
                         alt="User profile picture">

                    <h3 class="profile-username text-center"> {{$user->full_name}} </h3>

                    <p class="text-muted text-center">{{$user->type}} </p>

                    <ul class="list-group list-group-unbordered">

                        <li class="list-group-item">
                            <b>@lang('site.user_type')</b> <a class="pull-right">{{ $user->type }}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!--------------------------------------------- end About -------------------------------------->

        <!------------------------------------ Tabs -------------------------------->
        <div class="col-md-9">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#activity" data-toggle="tab">@lang('site.main_info')</a></li>
                </ul>
                <div class="tab-content">
                    <div class="active tab-pane" id="activity">
                        <div class="box-body">
                            @if($user->count() > 0)
                                <table class="table table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th> @lang('site.full_name') </th>
                                        <th> @lang('site.email') </th>
                                        <th> @lang('site.mobile') </th>
                                        <th> @lang('site.type') </th>
                                        <th> @lang('site.city') </th>
                                        <th> @lang('site.image') </th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    <tr>
                                        <td> {{ $user->full_name }} </td>
                                        <td> {{ $user->email }} </td>
                                        <td> {{ $user->mobile }} </td>
                                        <td> {{ $user->type }} </td>
                                        @if($user->city_id != null)
                                            <td> {{ $user->city->name_ar }}-{{ $user->city->name_en }} </td>
                                        @else
                                            <td> Admin City</td>
                                        @endif
                                        <td><img src="{{ $user->ImagePath }}" style="width: 80px ; height:80px"></td>
                                    </tr>
                                    </tbody>
                                </table>
                            @else
                                <h2> @lang('site.no_data_found') </h2>
                            @endif
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</section>
<!-- /.content -->

@endsection