routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function () {
    return redirect()->route('dashboard.index');
})->middleware('auth');


Route::Group(['prefix' => 'dashboard', 'namespace' => 'Dashboard', 'middleware' => 'auth'], function () {

    route::get('/index', 'HomeController@index')->name('dashboard.index')->middleware('auth');


    //============= Provider Routes
    Route::resource('providers', 'ProviderController');

//    Route::Group([ 'middleware' => 'permissions'], function () {

        //============= Client Routes
        Route::resource('users', 'UserController');

        //============= Admin Routes
        Route::resource('admins', 'AdminController');


        //================ Notifications Routes =========
        Route::post('send/notify', 'NotificationController@sendNotify')->name('send_notify');


        //================ Address Routes =========
        Route::resource('address', 'AddressController');

        //==============City Routes
        Route::resource('city', 'CityController');


        //===============Category Routes
        Route::resource('categories', 'CategoryController');


        //============================= Products Routs ================================================
        Route::resource('products', 'ProductController');


        //=============== Advertise Routs==========================================
        Route::resource('advertises', 'AdvertisesController');


        //===============Settings Routs ============================================
        Route::get('settings', 'SettingController@index')->name('settings.index'); //
        Route::get('settings/update', 'SettingController@edit')->name('settings.edit');
        Route::post('settings', 'SettingController@update')->name('settings.update');

//});

    //=============================== Orders =====================================
    Route::resource('orders', 'OrderController');
    Route::get('orders/process/{order}', 'OrderController@process')->name('process.order');
    Route::get('orders/ship/{order}', 'OrderController@ship')->name('ship.order');
    Route::get('orders/deliver/{order}', 'OrderController@deliver')->name('deliver.order');


});

resources/views/dashboard/layouts/includes/aside.blade.php
<section class="sidebar">
    <div class="user-panel">
        <div class="pull-left image">
            <img src="{{ auth()->user()->ImagePath }}  " class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
            <p> {{ auth()->user()->full_name }} </p>
            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
    </div>

    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">{{ trans('site.main_menu') }}</li>
        <li>
            <a href=" {{route('dashboard.index')}} ">
                <i class="fa fa-dashboard"></i> <span> @lang('site.dashboard')</span>
                </span>
            </a>
        </li>


        <!-- My Profile -->
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-user"></i> <span>الملف الشخصي</span>
                    <span class="pull-right-container">
                             <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li>
                        @if (auth()->user()->hasRole('admin'))
                            <a href="{{ route('admins.show',auth()->user()->id) }}" class="fa fa-circle-o "> Profile</a>
                        @else
                            <a href="{{ route('providers.show',auth()->user()->id) }}" class="fa fa-circle-o "> Profile</a>
                        @endif
                    </li>
                </ul>
            </li>
    <!-- End My Profile  -->


        <!-- All Providers -->
        @if (auth()->user()->hasRole('admin'))
            @if(auth()->user()->hasPermission('read_users'))
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>@lang('site.providers')</span>
                        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{route('providers.index')}} "><i
                                        class="fa fa-circle-o"></i> @lang('site.preview_all')</a></li>
                        @if(auth()->user()->hasPermission('create_users'))
                            <li><a href="{{route('providers.create')}} "><i
                                            class="fa fa-circle-o"></i> @lang('site.create')
                                </a></li>
                        @endif
                    </ul>
                </li>
            @endif
        @endif
    <!-- End All Providers  -->

        <!-- All Users  -->
        @if (auth()->user()->hasRole('admin'))

            @if(auth()->user()->hasPermission('read_users'))
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>@lang('site.users')</span>
                        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{route('users.index')}} "><i
                                        class="fa fa-circle-o"></i> @lang('site.preview_all')</a></li>
                        @if(auth()->user()->hasPermission('create_users'))
                            <li><a href="{{route('users.create')}} "><i class="fa fa-circle-o"></i> @lang('site.create')
                                </a></li>
                        @endif
                    </ul>
                </li>
            @endif
        @endif
    <!-- End All users  -->

        <!-- All City -->
        @if (auth()->user()->hasRole('admin'))

            @if(auth()->user()->hasPermission('read_cities'))
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>@lang('site.cities')</span>
                        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{route('city.index')}}"><i
                                        class="fa fa-circle-o"></i> @lang('site.preview_all')</a></li>
                        @if(auth()->user()->hasPermission('create_cities'))
                            <li><a href="{{route('city.create')}} "><i class="fa fa-circle-o"></i> @lang('site.create')
                                </a>
                            </li>
                        @endif
                    </ul>
                </li>
            @endif
        @endif
    <!--End All City  -->

        <!-- All Category -->
        @if (auth()->user()->hasRole('admin'))
            @if(auth()->user()->hasPermission('read_categories'))
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>@lang('site.categories')</span>
                        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{route('categories.index')}}"><i
                                        class="fa fa-circle-o"></i> @lang('site.preview_all')</a></li>
                        @if(auth()->user()->hasPermission('create_categories'))
                            <li><a href="{{route('categories.create')}} "><i
                                            class="fa fa-circle-o"></i> @lang('site.create') </a></li>
                        @endif
                    </ul>
                </li>
            @endif
        @endif
    <!--End All Category  -->


        <!-- All products  -->
        @if (auth()->user()->hasRole('admin'))
            @if(auth()->user()->hasPermission('read_products'))
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>@lang('site.products')</span>
                        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{route('products.index')}}"><i
                                        class="fa fa-circle-o"></i> @lang('site.preview_all')</a></li>
                        @if(auth()->user()->hasPermission('create_products'))
                            <li><a href="{{route('products.create')}} "><i
                                            class="fa fa-circle-o"></i> @lang('site.create')
                                </a></li>
                        @endif
                    </ul>
                </li>
            @endif
        @endif
    <!-- End All products -->


        <!-- All orders -->
        @if (auth()->user()->hasRole('admin'))
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>{{trans('site.all-orders')}}</span>
                    <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
                </a>
                <ul class="treeview-menu">
                    <li class="active"><a href="{{route('orders.index')}}"><i
                                    class="fa fa-circle-o"></i> @lang('site.preview_all')</a></li>
                </ul>
            </li>
        @endif
    <!--End All orders -->

        <!-- All Advertises -->

        @if (auth()->user()->hasRole('admin'))
            <li class="treeview">
                <a href="{{ route('advertises.index') }}">
                    <i class="fa fa-dashboard"></i> <span>{{trans('site.advertises')}}</span>
                    <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
                </a>
                <ul class="treeview-menu">
                    <li class="active"><a href="{{route('advertises.index')}}"><i
                                    class="fa fa-circle-o"></i> @lang('site.preview_all')</a></li>
                    <li class="active"><a href="{{route('advertises.create')}}"><i
                                    class="fa fa-circle-o"></i> @lang('site.add')</a></li>
                </ul>
            </li>
        @endif
    <!--End All Advertises -->

        <!-- All Settings Admin -->
        @if (auth()->user()->hasRole('admin'))

            @if(auth()->user()->hasPermission('update_settings'))
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>@lang('site.settings')</span>
                        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{route('settings.index')}}"><i
                                        class="fa fa-circle-o"></i> @lang('site.preview_all')</a></li>
                    </ul>
                </li>
            @endif
        @endif
    <!--End All Settings Admin -->

        <!-- All Settings Providers -->
        {{--<li class="treeview">--}}
        {{--<a href="#">--}}
        {{--<i class="fa fa-dashboard"></i> <span>@lang('site.app_links')</span>--}}
        {{--<span class="pull-right-container">--}}
        {{--<i class="fa fa-angle-left pull-right"></i>--}}
        {{--</span>--}}
        {{--</a>--}}
        {{--<ul class="treeview-menu">--}}
        {{--<li class="active"><a href="{{route('privacy')}}"><i class="fa fa-circle-o"></i> @lang('site.privacy_policy')</a></li>--}}
        {{--<li><a href="{{route('terms')}}"><i class="fa fa-circle-o"></i> @lang('site.terms')</a></li>--}}
        {{--<li><a href="{{route('about')}} "><i class="fa fa-circle-o"></i> @lang('site.about_app') </a></li>--}}

        {{--</ul>--}}
        {{--</li>--}}
    <!--End All Settings Providers -->

        <!-- All  Admins -->
        @if (auth()->user()->hasRole('admin'))
            @if(auth()->user()->hasPermission('read_users'))
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>@lang('site.admins')</span>
                        <span class="pull-right-container">
                          <i class="fa fa-angle-left pull-right"></i>
                       </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{route('admins.index')}} "><i
                                        class="fa fa-circle-o"></i> @lang('site.preview_all')</a></li>
                        @if(auth()->user()->hasPermission('create_users'))
                            <li><a href="{{route('admins.create')}} "><i
                                            class="fa fa-circle-o"></i> @lang('site.create')
                                </a></li>
                        @endif
                    </ul>
                </li>
        @endif
    @endif
    <!--End All  Admins -->

    </ul>
</section>

resources/views/dashboard/layouts/includes/errors.blade.php
    @if(count($errors)>0)
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
            <li> {{$error}} </li>
            @endforeach
        </ul>
    </div>
    @endif



    @if(session('success'))

    <div class="alert alert-success">
        {{session('success')}}
    </div>

    @endif



    @if(session('error'))

    <div class="alert alert-danger">
        {{session('error')}}
    </div>

    @endif

resources/views/dashboard/layouts/includes/footer.blade.php
<div class="pull-right hidden-xs">
  <b>Version</b> 2.4.18
</div>
<center><strong>Copyright &copy; 2020 <a href="#">RMAL</a>.</strong></center>

resources/views/dashboard/layouts/includes/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Car-Cap| Dashboard</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{{ asset('public/dashboard_files/bower_components/bootstrap/dist/css/bootstrap.min.css') }}  ">
<!-- Ionicons -->
<link rel="stylesheet" href="{{ asset('public/dashboard_files/bower_components/Ionicons/css/ionicons.min.css') }}  ">
<!-- skins -->
<link rel="stylesheet" href="{{ asset('public/dashboard_files/css/skins/_all-skins.min.css') }}  ">
<!-- Morris chart -->
<link rel="stylesheet" href="{{ asset('public/dashboard_files/bower_components/morris.js/morris.css') }}  ">
<link rel="stylesheet" href="{{ asset('public/dashboard_files/css/noty.css') }}  ">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
<script src="https://kit.fontawesome.com/e0a17cc3c7.js" crossorigin="anonymous"></script>


@if(app()->getlocale()== 'ar' )

<link rel="stylesheet" href="{{ asset('public/dashboard_files/css/AdminLTE-rtl.min.css') }}">
<link href="https://fonts.googleapis.com/css?family=Cairo:400,700" rel="stylesheet">
<link rel="stylesheet" href="{{ asset('public/dashboard_files/css/bootstrap-rtl.min.css') }}">
<link rel="stylesheet" href="{{ asset('public/dashboard_files/css/rtl.css') }}">

@else
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
<link rel="stylesheet" href="{{ asset('public/dashboard_files/css/AdminLTE.min.css') }}">

@endif

resources/views/dashboard/layouts/includes/header.blade.php
 <!-- Logo -->
 <a href="index2.html" class="logo">
   <!-- mini logo for sidebar mini 50x50 pixels -->
   <span class="logo-mini"><b>C</b>ar</span>
   <!-- logo for regular state and mobile devices -->
   <span class="logo-lg"><b>Car</b>Cap</span>
 </a>
 <!-- Header Navbar: style can be found in header.less -->
 <nav class="navbar navbar-static-top">
   <!-- Sidebar toggle button-->
   <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
     <span class="sr-only">Toggle navigation</span>
   </a>

   <div class="navbar-custom-menu">
     <ul class="nav navbar-nav">
       <!-- Messages: style can be found in dropdown.less-->
       <li class="dropdown messages-menu">
         {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown">--}}
           {{--<i class="fa fa-envelope-o"></i>--}}
           {{--<span class="label label-success">4</span>--}}
         {{--</a>--}}
         <ul class="dropdown-menu">
           {{--<li class="header">You have 4 messages</li>--}}
           {{--<li>--}}
             {{--<!-- inner menu: contains the actual data -->--}}
             {{--<ul class="menu">--}}
               {{--<li>--}}
                 {{--<!-- start message -->--}}
                 {{--<a href="#">--}}
                   {{--<div class="pull-left">--}}
                     {{--<img src=" {{ asset('public/dashboard_files/img/user2-160x160.jpg') }} " class="img-circle" alt="User Image">--}}
                   {{--</div>--}}
                   {{--<h4>--}}
                     {{--Support Team--}}
                     {{--<small><i class="fa fa-clock-o"></i> 5 mins</small>--}}
                   {{--</h4>--}}
                   {{--<p>Why not buy a new awesome theme?</p>--}}
                 {{--</a>--}}
               {{--</li>--}}
               {{--<!-- end message -->--}}
               {{--<li>--}}
                 {{--<a href="#">--}}
                   {{--<div class="pull-left">--}}
                     {{--<img src=" {{ asset('public/dashboard_files/img/user3-128x128.jpg') }} " class="img-circle" alt="User Image">--}}
                   {{--</div>--}}
                   {{--<h4>--}}
                     {{--Sales Department--}}
                     {{--<small><i class="fa fa-clock-o"></i> Yesterday</small>--}}
                   {{--</h4>--}}
                   {{--<p>Why not buy a new awesome theme?</p>--}}
                 {{--</a>--}}
               {{--</li>--}}
               {{--<li>--}}
                 {{--<a href="#">--}}
                   {{--<div class="pull-left">--}}
                     {{--<img src=" {{ asset('public/dashboard_files/img/user4-128x128.jpg') }} " class="img-circle" alt="User Image">--}}
                   {{--</div>--}}
                   {{--<h4>--}}
                     {{--Reviewers--}}
                     {{--<small><i class="fa fa-clock-o"></i> 2 days</small>--}}
                   {{--</h4>--}}
                   {{--<p>Why not buy a new awesome theme?</p>--}}
                 {{--</a>--}}
               {{--</li>--}}
             {{--</ul>--}}
           {{--</li>--}}
           {{--<li class="footer"><a href="#">See All Messages</a></li>--}}
         </ul>
       </li>
       <!-- Notifications: style can be found in dropdown.less -->
       <li class="dropdown notifications-menu">
         {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown">--}}
           {{--<i class="fa fa-bell-o"></i>--}}
           {{--<span class="label label-warning">{{ auth()->user()->notifications->count() }}</span>--}}
         {{--</a>--}}
         {{--<ul class="dropdown-menu">--}}
           {{--@foreach(App\Notification::where('notified_user_id' , auth()->user()->id)->get() as $notification)--}}
           {{--<li class="header">{{ $notification->title ?? trans('site.no_data_found') }}</li>--}}
           {{--@endforeach--}}
           {{--<li class="footer"><a href="#">View all</a></li>--}}
         {{--</ul>--}}
       </li>
       <!-- Tasks: style can be found in dropdown.less -->
       <li class="dropdown tasks-menu">
         {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown">--}}
           {{--<i class="fa fa-flag-o"></i>--}}
           {{--<span class="label label-danger">9</span>--}}
         {{--</a>--}}
         {{--<ul class="dropdown-menu">--}}
         {{--</ul>--}}
       </li>
       <!-- User Account: style can be found in dropdown.less -->
       <li class="dropdown user user-menu">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown">
           <img src=" {{ auth()->user()->ImagePath }}  " class="user-image" alt="User Image">
           <span class="hidden-xs">{{ auth()->user()->full_name }}</span>
         </a>
         <ul class="dropdown-menu">
           <!-- User image -->
           <li class="user-header">
             <img src=" {{ auth()->user()->ImagePath }} " class="img-circle" alt="User Image">

             <p>
               {{auth()->user()->full_name}} - {{auth()->user()->type}}

             </p>
           </li>
           <!-- Menu Body -->
           <li class="user-body">
             <div class="row">
               <div class="col-xs-4 text-center">
                 {{--<a href="{{ route('pending.products') }}">{{ trans('site.pending_products') }}</a>--}}
               </div>
               {{--<div class="col-xs-4 text-center">--}}
                 {{--<a href="#">Sales</a>--}}
               {{--</div>--}}
               {{--<div class="col-xs-4 text-center">--}}
                 {{--<a href="#">Friends</a>--}}
               {{--</div>--}}
             </div>
             <!-- /.row -->
           </li>
           <!-- Menu Footer-->
           <li class="user-footer">
             <div class="pull-left">
               @if (auth()->user()->hasRole('admin'))
               <a href="{{ route('admins.show',auth()->user()->id) }}" class="btn btn-default btn-flat">Profile</a>
                 @else
                 <a href="{{ route('providers.show',auth()->user()->id) }}" class="btn btn-default btn-flat">Profile</a>
               @endif
             </div>
             <div class="pull-right">
               <form action="{{ route('logout') }}" method="POST">
                 @csrf
                 <button type="submit">@lang('site.logout')</button>
               </form>
             </div>
           </li>
         </ul>
       </li>
       <!-- Control Sidebar Toggle Button -->
       <li>
         <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
       </li>
     </ul>
   </div>
 </nav>

resources/views/dashboard/layouts/includes/page_header.blade.php
<h1>
  Dashboard
  <small>Control panel</small>
</h1>
<ol class="breadcrumb">
  <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Dashboard</li>
</ol>

resources/views/dashboard/layouts/includes/scripts.blade.php
<script src="{{ asset('public/dashboard_files/bower_components/jquery/dist/jquery.min.js') }}  "></script>
<!-- jQuery UI 1.11.4 -->
<script src=" {{ asset('public/dashboard_files/bower_components/jquery-ui/jquery-ui.min.js') }}  "></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src=" {{ asset('public/dashboard_files/bower_components/bootstrap/dist/js/bootstrap.min.js') }}  "></script>
<!-- Morris.js charts -->
<script src=" {{ asset('public/dashboard_files/bower_components/raphael/raphael.min.js') }}  "></script>
<script src=" {{ asset('public/dashboard_files/bower_components/morris.js/morris.min.js') }}  "></script>
<!-- Sparkline -->
<script src=" {{ asset('public/dashboard_files/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js') }}  "></script>
<!-- jvectormap -->
<script src=" {{ asset('public/dashboard_files/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}  "></script>
<script src=" {{ asset('public/dashboard_files/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}  "></script>
<!-- jQuery Knob Chart -->
<script src=" {{ asset('public/dashboard_files/bower_components/jquery-knob/dist/jquery.knob.min.js') }}  "></script>
<!-- daterangepicker -->
<!-- datepicker -->
<script src=" {{ asset('public/dashboard_files/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}  "></script>
<!-- Bootstrap WYSIHTML5 -->
<script src=" {{ asset('public/dashboard_files/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}  "></script>
<!-- Slimscroll -->
<script src=" {{ asset('public/dashboard_files/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}  "></script>
<!-- FastClick -->
<script src=" {{ asset('public/dashboard_files/bower_components/fastclick/lib/fastclick.js') }}  "></script>
<!-- AdminLTE App -->
<script src="{{ asset('public/dashboard_files/js/adminlte.min.js') }}  "></script>
<script src="{{ asset('public/dashboard_files/js/noty.min.js') }}  "></script>


<script>
  //delete
  $('.delete').click(function(e) {

    var that = $(this)

    e.preventDefault();

    var n = new Noty({
      text: "@lang('site.confirm_delete')",
      type: "warning",
      killer: true,
      buttons: [
        Noty.button("@lang('site.yes')", 'btn btn-success mr-2', function() {
          that.closest('form').submit();
        }),

        Noty.button("@lang('site.no')", 'btn btn-primary mr-2', function() {
          n.close();
        })
      ]
    });

    n.show();

  }); //end of delete


  // image preview
  $(".image").change(function() {

    if (this.files && this.files[0]) {
      var reader = new FileReader();

      reader.onload = function(e) {
        $('.image-preview').attr('src', e.target.result);
      }

      reader.readAsDataURL(this.files[0]);
    }

  });
</script>